### ISSUE TITLE
Can anyone help me in explaining why cachecontrol of not caching url?

### ISSUE THREAD

**Issue by p0psicles** [ionrock/cachecontrol#116]
This is the url i'm testing with:
http://thetvdb.com/api/GetSeries.php?seriesname=breaking+bad&language=en

It's returning xml? Might it have something to do with that?

**Comment by int-ua** [comment]
Can it be #111 ?

**Comment by p0psicles** [comment]
I dont know. Maybe not caching the url is valid. Could have something todo that XML isnt supposed to be cached?? I can' t figuren it out. Was hoping someone is Willing to analyze the response (headers and comlntent) to see of this is A bug?

**Comment by ionrock** [comment]
CacheControl comes with a command line tool called 'doesitcache' to help determine whether a resource should be cacheable. Hope it helps!

**Comment by ionrock** [comment]
@p0psicles Unless you've found out something more detailed we can work from, I'm going to go ahead and close this. Feel free to open another issue if you have something more concise you think is failing.

**Comment by p0psicles** [comment]
Sure, thnx for the help!
