### ISSUE TITLE
Will there be a release soon?

### ISSUE THREAD

**Issue by eads** [ionrock/cachecontrol#121]
Is there any chance there will be a new release any time soon? 

I'm exploring using CacheControl with [elex](https://github.com/newsdev/elex). 

It's not entirely clear to me why yet (and I've been digging through the code quite a bit) but in the current released version, I can't get CacheControl to properly cache responses from a particular API using the filesystem cache. When I run with the latest github version, it works without fail. 

The response is not chunked. However, from what I've been able to tell, in the current version the response is just never written to disk, while in the latest version on master, it is. That makes me think the changes to file closing might solve the issue I'm seeing. 

I'm going to dig around more and see what I can turn up. However, given that it Just Works Now, is there a chance of rolling an 0.11.7 version any time soon? 

Thanks for the library, it is pretty nifty!

**Comment by ionrock** [comment]
Hi @eads! Thanks for creating the issue. I've actually been hoping to get some feedback from other users. I'm double checking that pip doesn't have any problems and will plan on pushing a release once that is confirmed. I'll update this ticket when that happens. 

Thanks again for testing the latest head!

**Comment by eads** [comment]
Awesome! Happy to help with testing. NPR & NYT are collaborating a project to get election data from the Associated Press' API; they want us to implement caching (and we've been planning it anyway) and cachecontrol seems like the thing to use. The API definitely has some quirks.

**Comment by eads** [comment]
Closing -- we'll use the bleeding edge version for a while longer.
