### ISSUE TITLE
Should heuristic apply regardless of status code?

### ISSUE THREAD

**Issue by eads** [ionrock/cachecontrol#123]
In my attempts to debug #122 (which turned out to be a quirk of my API provider), [I implemented a heuristic](https://github.com/newsdev/elex/blob/0121-response-caching/elex/cachecontrol_heuristics.py). The heuristic simply removes the max-age cache-control header. Voila, the etag-based caching worked, until the first cache hit (or so it seems). Once I got a cache hit, the max-age based debug messages were popping up again. 

What I realized is that the heuristic isn't applied to 304 responses (or 301s). My suspicion is that it should be -- [I moved the heuristic outside the conditional](https://github.com/eads/cachecontrol/commit/db28cafcdb1237309fd6b619c6c3319a014fd353) and now it seems to be working the way I would expect.

I need to dig around more -- this could be a case of getting age-related debug messages but the underlying mechanism still working correctly, but as far as I can tell now, not applying heuristics to 304s is a minor bug.

**Comment by eads** [comment]
Sorry to bother you on this but do you have any plans to take a look at this and roll a release any time soon? No worries if you can't; if you're swamped I think what we'll do is roll a special release of our fork called elex-cachecontrol so that our package can use it as a dependency. In that case we'll put a big ass disclaimer on it and direct people to the main library for their needs, and then switch to the official version whenever you have a chance to take a look.

(fwiw we appreciate everything you've done with this and I'm not trying to be annoying)

**Comment by ionrock** [comment]
@eads I took a look! Thanks for the PR! I'm happy to do a release as soon as we wrap up that PR.

**Comment by ionrock** [comment]
Going ahead and closing this with 0.11.7 released. Thanks @eads!
