### ISSUE TITLE
CacheController.cache_response is never called for chunked content bodies

### ISSUE THREAD

**Issue by jscholes** [ionrock/cachecontrol#126]
If you access [this URL](https://api.spotify.com/v1/search?q=jim%20croce&type=track), the API endpoint returns simple JSON, as you'd expect.  However, the response body seems to be chunked.

    >>> requests.get('https://api.spotify.com/v1/search?q=jim%20croce&type=track').headers.get('transfer-encoding')
    'chunked'

As a result, even though the appropriate caching headers are set, cachecontrol is unable to cache the response, due to the use of cachecontrol.filewrapper.CallbackFileWrapper (presumably response._fp is never explicitly closed when content is chunked).

    jscholes@web:~$ curl "https://api.spotify.com/v1/search?q=jim%20croce&type=track" -I
    HTTP/1.1 200 OK
    Server: nginx
    Date: Tue, 19 Jul 2016 00:29:22 GMT
    ...
    Cache-Control: public, max-age=7200

    DEBUG: Looking up "https://api.spotify.com/v1/search?q=jim%20croce&type=track" in the cache
    DEBUG: No cache entry available

If we explicitly set response.chunked to False for this request:

    DEBUG: Looking up "https://api.spotify.com/v1/search?q=jim%20croce&type=track" in the cache
    DEBUG: No cache entry available
    DEBUG: Updating cache with response from "https://api.spotify.com/v1/search?q=jim%20croce&type=track"
    DEBUG: Caching b/c date exists and max-age > 0

**Comment by hartym** [comment]
I struggled a lot with this, thanks for this explanation @jscholes! Any chance you found an easily applicable temporary workaround?

**Comment by jscholes** [comment]
Sadly not, I just switched to using httplib2 instead.

**Comment by hartym** [comment]
Looks like some work has been done in master, not released to PyPI : e170553
Going to test this against my codebase.

**Comment by hartym** [comment]
(works for me !)

**Comment by ionrock** [comment]
I believe this has released to PyPI with 0.11.7. Please reopen this if it doesn't fix your issue.
