### ISSUE TITLE
Cachecontrol prints out a notice about the optional requirements lockfile, even if we don't need it.

### ISSUE THREAD

**Issue by hartym** [ionrock/cachecontrol#130]
Importing RedisCache will print out the following notice even if we don't need it, because it is present in the package's **init** file 

```
NOTE: In order to use the FileCache you must have
    lockfile installed. You can install it via pip:
      pip install lockfile
```

Probably, this warning should go in the caches/file_cache.py file, and even better, it should probably be switched to something that is either fatal or harmless for stdout (using logging?).

See https://github.com/ionrock/cachecontrol/blob/master/cachecontrol/caches/__init__.py

Let me know if I can propose a patch for this.

**Comment by ionrock** [comment]
@hartym A patch would be great! Thanks for submitting the issue.

**Comment by jezdez** [comment]
This can be closed now I think, @ionrock.

**Comment by ionrock** [comment]
Indeed! Thanks!
