### ISSUE TITLE
'Redis' object has no attribute 'disconnect'

### ISSUE THREAD

**Issue by kirberich** [ionrock/cachecontrol#149]
Hi!

I just started using CacheControl with redis in a project, and while the caching itself works great, I'm running into problems when CacheControl tries to disconnect from redis, where it's calling a `disconnect` method on the redis object that doesn't exist.

I haven't been able to dig much deeper into this yet, some pointers would be much appreciated! I'll try to find out more about this tomorrow.

```python
.virtualenv/lib/python3.6/site-packages/requests/sessions.py:369: in __exit__
    self.close()
.virtualenv/lib/python3.6/site-packages/requests/sessions.py:690: in close
    v.close()
.virtualenv/lib/python3.6/site-packages/cachecontrol/adapter.py:129: in close
    self.cache.close()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <cachecontrol.caches.redis_cache.RedisCache object at 0x10f6f60f0>

    def close(self):
>       self.conn.disconnect()
E       AttributeError: 'Redis' object has no attribute 'disconnect'

.virtualenv/lib/python3.6/site-packages/cachecontrol/caches/redis_cache.py:41: AttributeError
```

**Comment by ionrock** [comment]
@kirberich unfortunately, that backend isn't very well supported. It shouldn't be hard to fix if you're interested. I'm happy to merge a fix as well. That said, I'm unable to try and get a fix right now.

**Comment by kirberich** [comment]
@ionrock thanks for the quick reply! 

I've sent a pull request that hopefully fixes this issue, it really just removes the connection closing from the RedisCache, which I think is the right thing to do with a redis cache that uses connection pooling.

Please let me know if you think this isn't the right fix!

Cheers
Rob
