### ISSUE TITLE
RedisCache should use built-in expiration

### ISSUE THREAD

**Issue by Schnouki** [ionrock/cachecontrol#15]
Redis has an excellent support for expiration: when adding a key, you can specify in how many seconds it will expire and be automatically deleted. It would be great if `RedisCache` could use that when there's a `max-age` or `expires` header in the response.

**Comment by ionrock** [comment]
After leaving this sitting for way too long, I'm going to close this ticket. The better tact is to ensure we have some more hook points in the cache storage API and support a better storage ecosystem, similar to Flask and its blueprints model. 

If you have thoughts on how best to do this, please let me know!
