### ISSUE TITLE
Make msgpack optional?

### ISSUE THREAD

**Issue by sybrenstuvel** [ionrock/cachecontrol#160]
We use CacheControl in the [Blender Cloud add-on](https://cloud.blender.org/services#blender-addon) for [Blender](https://www.blender.org/). Due to the wide range of platforms Blender can run on, binary Python packages are very impractical to use. So, in order to bundle CacheControl with a Blender add-on, we need to restrict ourselves to pure-Python packages.

Would it be an option to make msgpack an optional feature? If not, we're bound to limit ourselves to older versions of CacheControl.

**Comment by ionrock** [comment]
@sybrenstuvel My understanding is that package should default to a pure python implementation when it is unable to build the C extensions. Is it possible to include the pure python implementation explicitly as a wheel in your `wheels` directory?

@dstufft did you have any thoughts on this?

**Comment by dstufft** [comment]
I'm not sure how Blender is installing the libraries it depends on, but you can certainly install msgpack without using the C binary part of msgpack and only using the pure python implementation. I think in pip we just delete the .so files during our bundling process.

**Comment by djazo** [comment]
Blender has bundled python with it, and addons need to install required dependencies with them.
Thus wheels.

I made dirty hack to use v2 serialization if msgpack is not installed.

#161 

It's this or removing .so from msgpack wheel while bundling addon. Some zipfile editing.

**Comment by sybrenstuvel** [comment]
@dstufft can msgpack be packaged into a wheel without even building the binary part?

**Comment by dstufft** [comment]
It'll do that if you cause the compilation to fail in some way. If you're doing it on a Posix machine, ``CC=/bin/false python setup.py bdist_wheel`` should do it I think.

**Comment by djazo** [comment]
I get whl with cp36 tags even disabling binaries. Cosmetic, doesn't matter how things work, but still annoying. =)

**Comment by dstufft** [comment]
Ah yea, that's a bit of a bug-ish since the thing wheel uses to detect if something is a binary or not is "Was an ``Extension`` passed into ``setup()`` and the way msgpack implemetns the fallback is to just no-op the extension building command if it fails to compile.

That could be remedied on msgpack's side though.

**Comment by djazo** [comment]
@dstufft I'd say s/could/should. So we close this and hope msgpack will get update?

**Comment by ionrock** [comment]
FWIW, that is what I'd prefer. I can certainly appreciate the deployment frustrations, but I'd rather avoid adding deployment concerns to this package specifically. Thanks @dstufft for the help!

**Comment by hexagonrecursion** [comment]
```shell
~ pip download --no-binary=':all:' msgpack
Collecting msgpack
  Downloading msgpack-1.0.2.tar.gz (123 kB)
     |████████████████████████████████| 123 kB 1.4 MB/s 
Saved ./msgpack-1.0.2.tar.gz
Successfully downloaded msgpack
~ which gcc
/usr/bin/which: no gcc in (/home/user/.conda/envs/py3/bin:/home/user/.local/bin:/home/user/bin:/usr/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin)
~ pip install wheel
Requirement already satisfied: wheel in ./.conda/envs/py3/lib/python3.9/site-packages (0.36.2)
~ pip install ./msgpack-1.0.2.tar.gz 
Processing ./msgpack-1.0.2.tar.gz
Building wheels for collected packages: msgpack
  Building wheel for msgpack (setup.py) ... done
  Created wheel for msgpack: filename=msgpack-1.0.2-cp39-cp39-linux_x86_64.whl size=15818 sha256=089e25abf6c1880e1fd7cb964ba43d07dadaae001c287995fd5a19b7ff0c9ca5
  Stored in directory: /home/user/.cache/pip/wheels/2e/4a/6f/558a36d32ae40b8442f4f14bd6d55cb58d446c77a95daf01ab
Successfully built msgpack
Installing collected packages: msgpack
Successfully installed msgpack-1.0.2
~ python -c 'import msgpack; print(msgpack.Packer.__module__)'
msgpack.fallback
```

**Comment by sybrenstuvel** [comment]
> Could you please elaborate why you need a pure python wheel?

It's for inclusion in the [Blender Cloud add-on](https://cloud.blender.org/services) for Blender. Since Blender can be used on various different platforms, having to deal with only Python code for your add-on makes building & distributing it a lot simpler.

**Comment by hexagonrecursion** [comment]
Can you elaborate on how the distribution and installation process for the addon works? Does it work like this:
1. wheels are downloaded from pypi and added to a zip archive under blender_cloud/wheels
2. the archive is published
3. users download and install it
    1. the wheels are installed via pip

**Comment by sybrenstuvel** [comment]
> Can you elaborate on how the distribution and installation process for the addon works? Does it work like this:
Almost.

>     1. wheels are downloaded from pypi and added to a zip archive under blender_cloud/wheels
They are not added to a ZIP archive, but the wheel files themselves are placed under `blender_cloud/wheels`

>     2. the archive is published
>     3. users download and install it
Yes
>     4. the wheels are installed via pip
Nope, they're added to `sys.path` and Python can import the modules directly from them.

**Comment by hexagonrecursion** [comment]
> they're added to `sys.path` and Python can import the modules directly from them.

I assume you are aware of https://www.python.org/dev/peps/pep-0427/#is-it-possible-to-import-python-code-directly-from-a-wheel-file.

> Technically, due to the combination of supporting installation via simple extraction and using an archive format that is compatible with zipimport, a subset of wheel files do support being placed directly on sys.path. However, while this behaviour is a natural consequence of the format design, actually relying on it is generally discouraged.

more in-depth discussion at the link.

I 3 possible paths forward:
1. I can try figuring out how to make a pure *importable wheel* of msgpack
2. I can try figuring out how to make an [egg](https://setuptools.readthedocs.io/en/latest/userguide/commands.html#bdist-egg-create-a-python-egg-for-the-project) of msgpack. Note: unlike wheels, eggs are *designed* to be importable. 
3. run pip install during the installation to install wheels the way they are intended to be installed

**Comment by sybrenstuvel** [comment]
The most important for me is the pure-Python-ness of the package. An egg file would certainly be appreciated.

Installing via pip is not really an option; ideally Blender would have some namespacing per add-on, where dependencies of one add-on would not be available to others. This would make it possible to bundle different versions of dependencies with different add-ons, but it's something that has to be addressed on the Blender side. This is just an illustration why pip-installing wouldn't be preferred.

**Comment by hexagonrecursion** [comment]
Using the code from https://github.com/msgpack/msgpack-python/pull/467 I was able to build an egg that passes the `msgpack-python` testsuite.
```sh
pip install setuptools pytest
MSGPACK_PUREPYTHON=1 ./setup.py bdist_egg
cd dist/
PYTHONPATH=./msgpack-1.0.2-py3.9.egg pytest ../test/
...
116 passed
```

Assuming you are not afraid to build your own eggs when preparing a new release you are all set.

**Comment by OrangeDog** [comment]
> Could you please elaborate why you need a pure python wheel?

Because you cannot build extensions on e.g. default `-alpine` Docker containers. Trying to install `msgpack` when it does not provide a wheel for the platform will fail.

There is an alternate package, `msgpack-pure`, that can be used in this situation, but `CacheControl` has to declare the optional dependencies correctly so `pip` doesn't fail.

> msgpack-pure is for environments on which C-extention cannot be installed/compiled, including hosting, Windows and Google App Engine.
