### ISSUE TITLE
Detect if response is from cache

### ISSUE THREAD

**Issue by sansbacon** [ionrock/cachecontrol#165]
Is there a method to detect if the response is from the cache? I read the documentation but didn't see any mention of this topic.

Thanks!

**Comment by ionrock** [comment]
@sansbacon there is a `from_cache` boolean that is added to the response that will be true if it was a cached response and false if it is not from the cache.

**Comment by chriseldredge** [comment]
Perhaps this is worthy of a separate issue, but I'm curious if there is a way to distinguish, when `from_cache` is true, between a cache hit versus a request that returns a `304 Not Modified` response.

It would be potentially useful for tracking statistics on cache hits versus successful revalidation.

Supposing there is not currently a way to do that, would you be open to a PR to add the capability? Any tips on how we could expose this information?

**Comment by ionrock** [comment]
@chriseldredge I'd say open a PR to try and add some instrumentation if you're interested. You could always try to monkey patch something as well in the meantime.
