### ISSUE TITLE
DictCache may not be thread-safe

### ISSUE THREAD

**Issue by NicolasLM** [ionrock/cachecontrol#174]
Locks must be held for reading and writing, if not a reader may read garbage caused by a writer modifying the structure.

The GIL and atomic operations of CPython are implementation details that should not be relied upon. In my opinion the lock should be held for read operations as well.

**Comment by NicolasLM** [comment]
The FileCache may suffer from the same problem, consider:
- Process A: set `/cache/foo`
  - Create file
  - Write half of the content and gets interrupted
- Process B:  get `/cache/foo`
  - Open file
  - Read it fully
- Process A:
  - Finish to write the content of the file

Process B ends up with a corrupted file.

**Comment by ionrock** [comment]
@NicolasLM I can see your concern, but in practice, I haven't seen reports of this being an issue. The file locking used creates a buffer to write all the content, then locks the file, then copies buffer to the file content. This reduces the chance of a collision by more than enough in practice. In the dict scenario, you are correct that we get some help from Python in that a dict set operation is protected by the GIL, but more importantly, that set operations ends up as only one CPU operation as well. 

All that said, if you've seen some behavior or have a specific use case where this is failing and a read lock would be helpful, I'm happy to discuss an implementation, but without a report of some issue, I don't think it is a good idea to add the extra locking given the conditions. 

Lastly, if you do have a highly concurrent system that demands more extensive protections, I'd consider creating your own store implementation that provides the necessary protection.

**Comment by NicolasLM** [comment]
This library saves users between a few ms and minutes each time a resource is fetched from the cache. I doubt users would mind the extra ns related to locking in exchange for the peace of mind of not risking silent data corruption, even if very unlikely.

That being said I understand your point and the ability to plug a different cache backend provides a workaround, so feel free to close this issue.
