### ISSUE TITLE
Should DictCache work in a uWSGI flask?

### ISSUE THREAD

**Issue by keiranmraine** [ionrock/cachecontrol#194]
I'm using CacheControl to cache the Google certificate in my flask app but I can only get this to work if I am using `FileCache` (verified through the logging messages of cachecontrol).

Am I missing something:

```
def verify_user(token):
    try:
        session = requests.session()
        cached_session = cachecontrol.CacheControl(session)
        this_request = google.auth.transport.requests.Request(session=cached_session)
```

Flask started under uwsgi as:

```
uwsgi --master --http-socket 0.0.0.0:8000 --processes 2 -w cgpaasAuth:app
```

I'd anticipated perhaps having to do a few requests to prime the cache in each process but it didn't seem to take.

Thanks

**Comment by ionrock** [comment]
I'm guessing that by creating a new session for each call, you're also instantiating a new in memory cache that isn't shared. By using the FileCache, it is able to read the data from the filesystem, even though each session gets its own instance of the FileCache. 

Here is a potential refactor:

```
google_cert_sess = cachecontrol.CacheControl(requests.Session())

def verify_user(token):
    try:
        this_request = google.auth.transport.requests.Request(session=google_cert_sess)
```

**Comment by keiranmraine** [comment]
Okay, thanks for confirming my suspicions.

I think file cache is going to be the safer technique for our use case.  I'd expect a session held for the life of the flask app (which could be hours/days) would become unstable with the TCP connection being disconnected.

**Comment by ionrock** [comment]
FWIW, I've used sessions for long running apps without any problems. Not to say you shouldn't use the FileCache, but just pointing out the connection handling in Requests is really stable and has been for a long time. Sticking with the in-memory cache would help avoid a dependency on the filesystem. That may not be a big deal, but if filesystem access ever did become an issue (containerizing an app maybe?) the in-memory cache will be helpful. Just something to consider.

Glad you got it sorted out!
