### ISSUE TITLE
Django cache

### ISSUE THREAD

**Issue by thenewguy** [ionrock/cachecontrol#250]
Would you accept a cache backend that uses Django's caching framework?

**Comment by ionrock** [comment]
I wouldn't be likely to accept it just because I don't have time to maintain it. That said, you're welcome to add to any documentation that a Django Cache is available and point people in that direction.

**Comment by thenewguy** [comment]
No problem. Closing - can you clarify about #251 - I didn't see any tests that explicity demonstrate expires is UTC, just [one use of it in the redis storage](https://github.com/ionrock/cachecontrol/blob/master/cachecontrol/caches/redis_cache.py#L23)
