### ISSUE TITLE
Include LICENSE in the generated wheels

### ISSUE THREAD

**Issue by pradyunsg** [ionrock/cachecontrol#255]
See https://github.com/cython/cython/pull/3982/files for an example of how to do so.

This is necessary since pip’s vendoring logic is being changed to allow using wheels preferentially. This means it would need to use a hard-coded URL for the license of this package, until this package adds a license directly.

**Comment by itamarst** [comment]
However, `pip`'s vendoring still didn't seem happy? Will investigate at some point since I suspect `pip` will want this as part of the update.

**Comment by pradyunsg** [comment]
IANAL but it seems like https://github.com/ionrock/cachecontrol/pull/226 removed the license text and added incorrect content in the Licenses/ directory. Right now, there's no copyright assignment line in the repository's license. Further, instead of using the license text that Apache provides (see https://www.apache.org/licenses/LICENSE-2.0#apply), that PR seems to have copied the raw license text -- which is not how you apply the license IIUC.

I think removing LICENSES/* files, adding a single LICENSE file (with the same content as removed in #226) and updating the setup.cfg would make the tooling work, as well as be the right thing to do.

**Comment by ionrock** [comment]
@pradyunsg Do you have a way to verify if #266 fixes the License bits?

**Comment by pradyunsg** [comment]
The easiest way would be to build a wheel with that commit, unzip it (wheels are zip files, with additional structure) and see whether there's a LICENSE.txt file in there.

As long as the licence file has COPYING or LICENSE in the name, it'll work just fine with the automation that pip uses.

**Comment by pradyunsg** [comment]
Thanks @ionrock! ^>^
