### ISSUE TITLE
Error when max-age is set

### ISSUE THREAD

**Issue by recursiveMake** [ionrock/cachecontrol#268]
When using the redis cachecontrol, I get an error when the max-age header is set.

```
expires = 900

    def set(self, key, value, expires=None):
        if not expires:
            self.conn.set(key, value)
        else:
>           expires = expires - datetime.utcnow()
E           TypeError: unsupported operand type(s) for -: 'int' and 'datetime.datetime'

pyenv/lib/python3.6/site-packages/cachecontrol/caches/redis_cache.py:23: TypeError
```

I believe this is because we set `expires_time` to an `int` [here](https://github.com/ionrock/cachecontrol/blob/master/cachecontrol/controller.py#L349) instead of a `datetime`.

**Comment by davegaeddert** [comment]
@recursiveMake I ran into the same issue. #269 is one potential solution...
