### ISSUE TITLE
No tests in pypi sdist tarball

### ISSUE THREAD

**Issue by dvzrv** [ionrock/cachecontrol#281]
Hi! I'm packaging this project for Arch Linux.

We usually try to rely on pypi.org for sdist tarballs to build from. In a packaging context we also run tests to ensure, that the given project is compatible with our own Python ecosystem. Unfortunately the tests are not included in the sdist tarball on pypi.org, so it would be awesome if you could add them there. It allows anyone to also rely on tests when they build a wheel from source! :)

**Comment by mr-c** [comment]
Debian would also appreciate the tests being in the sdist; currently we have to pull from GitHub to get the tests instead of the official PyPI releases: https://salsa.debian.org/python-team/packages/python-cachecontrol/-/blob/master/debian/watch#L5
