### ISSUE TITLE
Release 0.12.12 breaks code that attempts to `from tests.[...] import [...]`

### ISSUE THREAD

**Issue by LuisVerbally** [ionrock/cachecontrol#285]
Trying to import from my own `tests` module results in a `ModuleNotFound` error when using version 0.12.12

Reverting to 0.12.11 fixes the issue.

**Comment by dimbleby** [comment]
in a surprising reversal of usual conventions, the 0.12.11 release included tests in the binary distribution but not in the source distribution - see #281 and #282

0.12.12 does the opposite, which is what would be expected.

Presumably you were somehow relying on the faulty packaging.  You should fix your tests.

**Comment by frostming** [comment]
Closed by #287
