### ISSUE TITLE
cachecontrol is incompatible with Requests 2.30.0

### ISSUE THREAD

**Issue by pgjones** [ionrock/cachecontrol#292]
See https://github.com/psf/requests/issues/6437

**Comment by notenti** [comment]
This is probably as simple as pinning the `requests` version to be <2.30. I'll open up a PR

**Comment by notenti** [comment]
What would make more sense here? Pinning `requests` so it's <2.30? Or updating the logic so `strict` isn't referenced?

**Comment by elijahr** [comment]
The comment on that issue suggests this is from urllib3 >= 2 being used: https://github.com/psf/requests/issues/6437#issuecomment-1533357246

> this appears to be an incompatibility in cachecontrol with the new release of urllib3 2.0. strict is no longer a supported argument on the HTTPResponse class. For the time being you'll likely need to pin to an older version of urllib3 or work with the cachecontrol team to update their usage.

Perhaps the fix would be to check urllib3's major version and expect a different `HTTPResponse` shape based on whether it is 1 or greater than 1.

**Comment by notenti** [comment]
Based on [this diff](https://github.com/urllib3/urllib3/pull/2064/commits/8893ebef90316761b75565d931762c33b173d117#diff-008f01f06c84456177464927734cc849c073b1f3d13bfab947ff812a5b4ac965L591) it looks like `strict` isn't supported at all in python 3. Could we just do a plain ole `getattr` call to default to 0 if it's not present? Looks like that's what was happening upstream of this library anyways

**Comment by sww314** [comment]
I believe the issue is actually urllib > 2. 
Here is the issue in the urllib3 repo. As a work around pinning urllib version works.

The suggested `gettattr` solution seems like a clean fix in cachcontrol.

https://github.com/urllib3/urllib3/issues/3010

**Comment by sethmlarson** [comment]
Maintainer of urllib3 here! I'd recommend the `getattr` approach regardless of what gets done in urllib3 in the short-term, long-term the property won't be available on `HTTPResponse` or `HTTPConnection` (and defaults to `True` in terms of behavior).

**Comment by jonbeacherdomuso** [comment]
This issue came up today for us; the workaround was to use requests 2.29.0

**Comment by Shahard2** [comment]
> This issue came up today for us; the workaround was to use requests 2.29.0

It didn't help...
Any other solution?

**Comment by sww314** [comment]
We fixed by pinning urllib3: 

`urllib3==1.26.15 # https://pypi.org/project/urllib3/`

**Comment by rdbisme** [comment]
The lightest workaround is to set `urllib3<2`.

**Comment by Shahard2** [comment]
> We fixed by pinning urllib3:
> 
> `urllib3==1.26.15 # https://pypi.org/project/urllib3/`
> 
> The problem is not `requests`.

didn't work..

**Comment by Shahard2** [comment]
> The lightest workaround is to set `urllib3<2`.

Tried this one too... same error

**Comment by rdbisme** [comment]
> > The lightest workaround is to set `urllib3<2`.
> 
> Tried this one too... same error

I'm pretty sure this fixes the problem. I've deployed it on hundreds of projects using poetry that stopped working because of this. 

Can you elaborate what's not working? More details will help understand. :)

**Comment by sww314** [comment]
@Shahard2 you have something else wrong then. Old urllib3 works fine.

**Comment by ionrock** [comment]
@sethmlarson Hey! Is it safe to just drop the `strict` completely?

**Comment by sww314** [comment]
Seems like Python std library dropped support way back in Python 3.4: 

> Changed in version 3.4: The strict parameter was removed. HTTP 0.9-style “Simple Responses” are no longer supported.


https://docs.python.org/3/library/http.client.html#http.client.HTTPSConnection:~:text=HAS_SNI%20is%20true).-,Changed%20in%20version%203.4%3A%20The%20strict%20parameter%20was%20removed.%20HTTP%200.9%2Dstyle%20%E2%80%9CSimple%20Responses%E2%80%9D%20are%20no%20longer%20supported.,-Changed%20in%20version

**Comment by sethmlarson** [comment]
@ionrock It's safe to drop for urllib3 2.0 or Python 3. In Python 2 on urllib3 1.26.x there is still functionally a difference between strict=True/False.

Appreciate you jumping in to help here! Apologies for the suddenness of this issue surfacing, no one reported it during our prerelease period, unfortunately.

**Comment by dwhatley19** [comment]
> > > The lightest workaround is to set `urllib3<2`.
> > 
> > 
> > Tried this one too... same error
> 
> I'm pretty sure this fixes the problem. I've deployed it on hundreds of projects using poetry that stopped working because of this.
> 
> Can you elaborate what's not working? More details will help understand. :)

@rdbisme Pinning the version isn't working for me either. Using poetry and GitHub Actions and here is the output I get when building:

```
Step 16/20 : RUN poetry config virtualenvs.create false && poetry install --no-root $POETRY_ARGS
 ---> Running in df80379cd35d
Skipping virtualenv creation, as specified in config file.
Installing dependencies from lock file

Package operations: 76 installs, 6 updates, 6 removals

  • Removing distlib (0.3.6)
  • Removing filelock (3.9.0)
  • Removing pexpect (4.8.0)
  • Removing platformdirs (3.1.0)
  • Removing ptyprocess (0.7.0)
  • Removing virtualenv (20.20.0)
  • Installing pyasn1 (0.4.8)

  AttributeError

  'HTTPResponse' object has no attribute 'strict'

  at /usr/local/lib/python3.10/site-packages/cachecontrol/serialize.py:54 in dumps
       50│                 ),
       51│                 u"status": response.status,
       52│                 u"version": response.version,
       53│                 u"reason": text_type(response.reason),
    →  54│                 u"strict": response.strict,
       55│                 u"decode_content": response.decode_content,
       56│             ***
       57│         ***
       58│ 
```

Could it be that GitHub Actions uses its own version of cachecontrol which ignores anything set in `pyproject.toml`?

**Comment by xytxytxyt** [comment]
depending on your poetry version, it might be the case that poetry itself depends on the affected versions of requests/urllib3, separately from your project

in my case, poetry installs itself into a venv, so i found the venv, activated it, downgraded requests and urllib3 via `pip`, deactivated, and poetry worked fine thereafter

**Comment by rdbisme** [comment]
> > > > The lightest workaround is to set `urllib3<2`.
> > > 
> > > 
> > > Tried this one too... same error
> > 
> > 
> > I'm pretty sure this fixes the problem. I've deployed it on hundreds of projects using poetry that stopped working because of this.
> > Can you elaborate what's not working? More details will help understand. :)
> 
> @rdbisme Pinning the version isn't working for me either. Using poetry and GitHub Actions and here is the output I get when building:
> 
> ```
> Step 16/20 : RUN poetry config virtualenvs.create false && poetry install --no-root $POETRY_ARGS
>  ---> Running in df80379cd35d
> Skipping virtualenv creation, as specified in config file.
> Installing dependencies from lock file
> 
> Package operations: 76 installs, 6 updates, 6 removals
> 
>   • Removing distlib (0.3.6)
>   • Removing filelock (3.9.0)
>   • Removing pexpect (4.8.0)
>   • Removing platformdirs (3.1.0)
>   • Removing ptyprocess (0.7.0)
>   • Removing virtualenv (20.20.0)
>   • Installing pyasn1 (0.4.8)
> 
>   AttributeError
> 
>   'HTTPResponse' object has no attribute 'strict'
> 
>   at /usr/local/lib/python3.10/site-packages/cachecontrol/serialize.py:54 in dumps
>        50│                 ),
>        51│                 u"status": response.status,
>        52│                 u"version": response.version,
>        53│                 u"reason": text_type(response.reason),
>     →  54│                 u"strict": response.strict,
>        55│                 u"decode_content": response.decode_content,
>        56│             ***
>        57│         ***
>        58│ 
> ```
> 
> Could it be that GitHub Actions uses its own version of cachecontrol which ignores anything set in `pyproject.toml`?

Can you show how are you pinning the version? In your Dockerfile, before using `poetry` you need to install `urrlib3<2`. Your posted docker build log doesn't show how you have pinned the dependency.

**Comment by vamshiaruru-virgodesigns** [comment]
> > > > The lightest workaround is to set `urllib3<2`.
> > > 
> > > 
> > > Tried this one too... same error
> > 
> > 
> > I'm pretty sure this fixes the problem. I've deployed it on hundreds of projects using poetry that stopped working because of this.
> > Can you elaborate what's not working? More details will help understand. :)
> 
> @rdbisme Pinning the version isn't working for me either. Using poetry and GitHub Actions and here is the output I get when building:
> 
> ```
> Step 16/20 : RUN poetry config virtualenvs.create false && poetry install --no-root $POETRY_ARGS
>  ---> Running in df80379cd35d
> Skipping virtualenv creation, as specified in config file.
> Installing dependencies from lock file
> 
> Package operations: 76 installs, 6 updates, 6 removals
> 
>   • Removing distlib (0.3.6)
>   • Removing filelock (3.9.0)
>   • Removing pexpect (4.8.0)
>   • Removing platformdirs (3.1.0)
>   • Removing ptyprocess (0.7.0)
>   • Removing virtualenv (20.20.0)
>   • Installing pyasn1 (0.4.8)
> 
>   AttributeError
> 
>   'HTTPResponse' object has no attribute 'strict'
> 
>   at /usr/local/lib/python3.10/site-packages/cachecontrol/serialize.py:54 in dumps
>        50│                 ),
>        51│                 u"status": response.status,
>        52│                 u"version": response.version,
>        53│                 u"reason": text_type(response.reason),
>     →  54│                 u"strict": response.strict,
>        55│                 u"decode_content": response.decode_content,
>        56│             ***
>        57│         ***
>        58│ 
> ```
> 
> Could it be that GitHub Actions uses its own version of cachecontrol which ignores anything set in `pyproject.toml`?

Same issue here as well. Poetry install works just fine locally, but on github actions it fails.

**Comment by sarmadgulzar** [comment]
> We fixed by pinning urllib3:
> 
> `urllib3==1.26.15 # https://pypi.org/project/urllib3/`
> 
> The problem is not `requests`.

This works! In my case the `verify_id_token` from `firebase_admin.auth` was failing.

**Comment by orumaxon** [comment]
Hi!
Help, please, what is the final solution to the problem?
I got confused in discussions of different Issue.

I get the same error with dependencies:
cached-property = "1.5.2"
requests = "2.26.0"
urllib3 = "1.26.7"

What needs to be rolled back to which version ?

P.S.
Used a translator

**Comment by GuillermoOvejeroSanchez** [comment]
Hi! @vamshiaruru-virgodesigns @rdbisme 
I had same problem running CI/CD gitlab pipelines.

Installing poetry==1.4.2
And the installing deps, with these two pinned down worked for me.

urllib3==1.26.15
requests==2.30.0

**Comment by vamshiaruru-virgodesigns** [comment]
> Hi! @vamshiaruru-virgodesigns @rdbisme I had same problem running CI/CD gitlab pipelines.
> 
> Installing poetry==1.4.2 And then installing deps with these two pinned down worked for me.
> 
> urllib3==1.26.15 requests==2.30.0

Thank you, updating poetry version fixed it.

**Comment by tandav** [comment]
I've fixed this issue ` 'HTTPResponse' object has no attribute 'strict'` by updating poetry from `1.1.15` to latest `1.4.2`

**Comment by patrissia-mm** [comment]
pip install urllib3==1.26.15

**Comment by innomatics** [comment]
> I've fixed this issue ` 'HTTPResponse' object has no attribute 'strict'` by updating poetry from `1.1.15` to latest `1.4.2`

Poetry upgrade worked for me (pinning `urllib3==1.26.15` did not - got version solving failed)

**Comment by aakashrshah** [comment]
I have 1.4.2 and the problem persists. This is really annoying.

**Comment by woodruffw** [comment]
Given https://github.com/psf/requests/security/advisories/GHSA-j8r2-6x86-q33q, a fix here is increasingly important: packages that can't upgrade because of `CahceControl`'s incompatibility will remain vulnerable.

**Comment by sethmlarson** [comment]
@woodruffw Requests is still compatible with urllib3 1.26.x so people using cachecontrol can continue using urllib3 1.26.x until cachecontrol adds support for urllib3 2.x.

**Comment by frostming** [comment]
Hi, I have to move on to create a fork at https://github.com/frostming/cacheyou, with this issue addressed.

The long term plan is if this project can continue I will merge the changes back.

**Comment by frostming** [comment]
> It doesn't seem that a fork will help in the case where this library is used as a transitive dependency where all installed packages must be in a requirements.txt file (e.g., typical serverless/paas configuration).

agree, but it can mitigate the problem.

**Comment by garchaaman19** [comment]
> We fixed by pinning urllib3:
> 
> `urllib3==1.26.15 # https://pypi.org/project/urllib3/`
> 
> The problem is not `requests`.

This worked for me.
