### ISSUE TITLE
serialize.py function fails with HTTPResonse has no attribute "strict"

### ISSUE THREAD

**Issue by aleksaw** [ionrock/cachecontrol#293]
When running `pdm install` with no dependencies on python 3.10 and 3.11 I have just started experiencing at error stemming from [this line](https://github.com/ionrock/cachecontrol/blob/c05ef9eff1c9ac176481fb99e7a7188aa5b4e17b/cachecontrol/serialize.py#L54). I don't have a lot of information beyond this since this is for some reason called by `pdm sync/install`. I do know, that replacing the `response.strict` part with `True` got `pdm sync` to stop crashing.

**Comment by aleksaw** [comment]
I also get `[TypeError]: HTTPResponse.__init__() got an unexpected keyword argument 'strict'` from [this line](https://github.com/ionrock/cachecontrol/blob/c05ef9eff1c9ac176481fb99e7a7188aa5b4e17b/cachecontrol/serialize.py#L141)

**Comment by dairiki** [comment]
It has to do with the removal of the `strict` parameter and attribute from `HTTPResponse` in `urllib3>=2.0`.
([Changelog](https://github.com/urllib3/urllib3/blob/main/CHANGES.rst#200-2023-04-26), PR urllib3/urllib3#2064)

A workaround is to pin `urllib3<2`.

**Comment by dairiki** [comment]
I think this is a dup of #292.

**Comment by aleksaw** [comment]
Thanks @dairiki ! It seems indeed to be a duplicate.

**Comment by t0b3** [comment]
@ionrock now this commit is in - can you release a new version i.e. 0.12.13 for https://pypi.org/project/cachecontrol/#history ?
motivation: this would solve many downstream issues for others eg. depending on latest cachecontrol for CI jobs etc. i.e. those using poetry ...

**Comment by graingert** [comment]
@t0b3 looks like 0.13.1 is out

**Comment by woodruffw** [comment]
Yep, this should be fixed. Closing, please let me know if I missed something and I'll reopen.
