### ISSUE TITLE
SeparateBodyFileCache does not close the file

### ISSUE THREAD

**Issue by dimbleby** [ionrock/cachecontrol#302]
https://github.com/ionrock/cachecontrol/blob/81ef6ba27d3c2c81298a3fbad54bc3a8e44c22fe/cachecontrol/caches/file_cache.py#L156-L161

should be some sort of context manager, I would think.

**Comment by frostming** [comment]
Since the fp is passed to construct a `urllib3.HTTPResponse` and it will be closed by the response.

Can you give an example where the body isn't closed?

**Comment by dimbleby** [comment]
ah, you're probably right
