### ISSUE TITLE
support setting max size on cache store

### ISSUE THREAD

**Issue by requiredfield** [ionrock/cachecontrol#36]
IIUC, currently cache stores are allowed to grow without bound, is that right? If so, is there any interest in adding support for setting a max size on the cache store? If you're using a FileCache, for instance, and have a limited amount of disk space (e.g. you're on the AWS free tier), this would be useful.

For the simplest possible first pass at this, once the max size is reached, the cache store could simply decline to cache anything further, ideally notifying the user somehow (maybe if you use this setting you can pass in a logger). A less naive implementation could intelligently select items to evict from the cache to make room for additional ones, e.g. on the basis of hit rate. (Item with lowest hit rate gets evicted first; ties could be broken with item size and/or least recency of access. Actually, should look at how browsers do it.)

Thanks for your consideration, and for all the great work on cachecontrol!

**Comment by ionrock** [comment]
After playing around with this and not coming to any good solutions, I'm going to go ahead and close this ticket. The reason being is that I believe it is going to be better to let others implement a LRU (or some other size capping technique) in their own cache store. 

Obviously, if there is a good PR I'd be more than happy to merge it. Similarly, if the cache store needs information it doesn't get currently, that would be something else to consider.
