### ISSUE TITLE
BaseHeuristic.warning is insufficiently flexible to implement HTTP caching spec properly

### ISSUE THREAD

**Issue by ssokolow** [ionrock/cachecontrol#51]
According to the spec, you're supposed to return [warning 113](http://tools.ietf.org/html/rfc7234#section-5.5.4) if your cache has intentionally served up something more than 24 hours stale. However, you neglected to expose the response's information to `warning` so I can check how old the response is.

As is, I'm probably going to wind up overriding `BaseHeuristic.apply` instead, which grates on me since the docs say nothing about its API stability.

**Comment by ionrock** [comment]
Good call. I'll update the warning method signature to accept an optional response argument.

**Comment by ssokolow** [comment]
Not that I'm not grateful, but is the heuristics system young enough to get away with that?

If someone else already implemented a BaseHeuristic subclass and didn't use `*args` to catch unexpected input, adding a new argument will cause a `TypeError`.

**Comment by ionrock** [comment]
You are correct, it is in fact *very* young. I'll be releasing a major point release when this goes out to signify the API change.

**Comment by ssokolow** [comment]
In that case, I'm very glad I decided to rework this project now. Having the heuristics API, as immature as it is, will allow me to greatly simplify things.
