### ISSUE TITLE
"Caching Heuristics" example code has two typos

### ISSUE THREAD

**Issue by ssokolow** [ionrock/cachecontrol#52]
When I copy-pasted the example code from http://cachecontrol.readthedocs.org/en/latest/custom_heuristics.html#caching-heuristics into my program to serve as a starting point, my Flake8+PyLint integration warned me of several typos:

1. `cachecontrol.heuristic` doesn't exist. You missed an `s` at the end of that.
2. You use `headers` without defining it and then don't `return` it.
3. You didn't import `calendar` before using it.

(Which really makes me glad I already had plans to integration-test my Requests+CacheControl stack using [HTTPretty](http://falcao.it/HTTPretty/) to ensure it's actually behaving as intended. Would you like some of that test code once I've gotten around to writing it?)

**Comment by ionrock** [comment]
Great catch! Thanks for finding it. 

I'm always interested in better tests, so please feel free to share any integration tests in an issue or as a pull requests.
