### ISSUE TITLE
Documentation doesn't explain how to force-invalidate a cached value

### ISSUE THREAD

**Issue by ssokolow** [ionrock/cachecontrol#53]
I write various scripts which automate tasks in my daily life and, both as a courtesy to site owners and to make it harder for paranoid ones to be jerks, I always incorporate a minimum cache duration. (For most uses, something like "1 hour for 2xx/3xx, 5 minutes for 4xx/5xx", In the past, this was implemented as a separate wrapper layer around httplib2)

However, sometimes, I do need to force the cache to be ignored. Ideally, I'd like to have both of the following options available to me, but the docs say nothing about either one:

1. When using Time Priority caching, I'd like a way to invalidate the time and just use the ETag on a per-request basis.
2. For either caching strategy, I'd like a way to just invalidate and refresh the cache entry, period.

**Comment by ssokolow** [comment]
Ok, by poking around in the code, I confirmed that CacheControl obeys `no-cache`, `max-age`, and `min-fresh` in the request but completely ignores `max-stale`.

If I understand your code correctly, that means that I can just set `no-cache` in the request and CacheControl will obey that and refresh the cache without question.

However, I'm having trouble piecing together how the ETag handling works, so I'm unsure whether doing something that would result in `(freshness_lifetime > current_age) == False` would result in the "When using Time Priority caching, I'd like a way to invalidate the time and just use the ETag on a per-request basis." effect I'm also looking for.

Either way, this should all be in the docs.

**Comment by ionrock** [comment]
Thanks for looking at the code and finding max-stale seems to be ignored. I'll take a look. Obviously pull requests are gratefully accepted!

You are correct about passing a no-cache header. That is the best way to invalidate the cache.

ETags primarily work to make conditional requests rather than use the cache value without further contact with the server. That is why it is check after the time based caching has expired. The client will make a conditional request and the server should respond with a Not Modified, at which point CacheControl can use the cached value. This makes the functionality heavily dependent on the server's ability to appropriately respond to requests with conditional headers. 

Thanks for bringing up the lack of clarity in the docs. I'll try to revise that section. You are correct that they don't clearly convey the behavior. And again, PRs are always graciously accepted!

**Comment by ssokolow** [comment]
> Thanks for looking at the code and finding max-stale seems to be ignored.

No problem. I was walking my way through the relevant bit of HTTP 1.1 and it was an easy conclusion to come to when `ack -i max-stale /usr/local/lib/python2.7/dist-packages/cachecontrol/` was the only command I ran which returned without producing any output.

> And again, PRs are always graciously accepted!

At the moment, a rushed attempt to shift my sleep cycle has left me a bit jet-lagged and more in an analytical/investigative mood than a creative/authorial one, but I'll see if I can make room for a PR some time in the near future.

> ETags primarily work to make conditional requests rather than use the cache value without further contact with the server. That is why it is check after the time based caching has expired. The client will make a conditional request and the server should respond with a Not Modified, at which point CacheControl can use the cached value. This makes the functionality heavily dependent on the server's ability to appropriately respond to requests with conditional headers. 

I understand that. I'm just having trouble wrapping my somewhat tired mind around the simplest proper way to ignore an `Expires` header set by my `BaseHeuristic` subclass without also ignoring the ETag the way `no-cache` would.

**Comment by matkoniecz** [comment]
I see that it is closed, but documentation is still missing proper explanation how cache may be invalidated.

In case that 

>  And again, PRs are always graciously accepted!

is true for this issue - can you reopen it?

**Comment by matkoniecz** [comment]
Now I am trying where `no-cache` parameter should be passed. Currently I suspect that I need a special caching heurestic ( https://cachecontrol.readthedocs.io/en/latest/custom_heuristics.html#caching-heuristics )

**Comment by matkoniecz** [comment]
It seems that I cobbled together code that is capable of invalidating cache and forcing pages to be cached.

```
import requests
from cachecontrol import CacheControl

import calendar
from cachecontrol.heuristics import BaseHeuristic
from datetime import datetime, timedelta
from email.utils import parsedate, formatdate


class OneWeekHeuristic(BaseHeuristic):

    def update_headers(self, response):
        date = parsedate(response.headers['date'])
        expires = datetime(*date[:6]) + timedelta(weeks=1)
        return {
            'expires' : formatdate(calendar.timegm(expires.timetuple())),
            'cache-control' : 'public',
        }

    def warning(self, response):
        msg = 'Automatically cached! Response is Stale.'
        return '110 - "%s"' % msg


sess = CacheControl(requests.Session(), heuristic=OneWeekHeuristic())
url = "https://github.com/ionrock/cachecontrol/issues/53"
response = sess.get(url)
response = sess.get(url)
print(response.from_cache)
response = sess.get(url)
print(response.from_cache)
response = sess.get(
    "https://github.com/ionrock/cachecontrol/issues/53",
    headers={"cache-control": "no-cache"},
)
print(response.from_cache)
```
