### ISSUE TITLE
Documentation doesn't explain algorithm used to determine whether to cache based on time

### ISSUE THREAD

**Issue by ssokolow** [ionrock/cachecontrol#54]
I have a "cache for the greater of X and the site-specified cache duration" wrapper that I'd like to convert into a CacheControl heuristic but the documentation doesn't explain how the heuristics system actually interacts with Time Priority caching.

As such, I'm forced to dig around in the code to figure out which headers I have to override and in what ways to ensure the desired behaviour. (And while it is very nice, clean code, that's still a documentation bug)

**Comment by ionrock** [comment]
I totally agree! The heuristic code was a first pass for allowing the user to override the cache settings sent by a server. There is probably a good deal that can be improved, so thank you for exercising the code. 

The tactic I'm using with heuristics is to allow overriding headers. As you've noticed, it requires the user to understand the headers the server is sending. The reason for this tactic is to avoid adding code in the actual header analysis code that includes some sort of special cases. For example, I had considered adding something like a `x-cache-control-expires` header that could override the normal expires header, but that would mean corrupting the original request slightly in a way that is not really HTTP compliant. 

In the case where you just want to increase the specific cache duration you'd need to look at what caching headers are passed. It will be dependent on what headers are passed by the server. While I'm sure there are some best practices here to make this easier, I'd like to try and get a better idea from users (like yourself!) as to what headers to recommend that works reliably for different scenarios. 

Also, as I'm hoping you already found, there are a couple example heuristics in the code that might be helpful. I'll be using these examples in the documentation to help clarify how to create a custom heuristic. Similarly, if you have a heuristic you feel could be useful to others, please feel free to submit a pull request.

**Comment by ssokolow** [comment]
> Similarly, if you have a heuristic you feel could be useful to others, please feel free to submit a pull request. 

:smile: Once I feel confident with my closure for creating "cache for the greater of X and the site-specified cache duration" `Heuristic`s, I'll do just that... though that might slow things down a bit since, now, my perfectionist streak will drive me to investigate and mimic your unit tests in preparation for the PR, even if that means two different styles coexisting in my own program.
