### ISSUE TITLE
BaseHeuristic is too low-level to be the only API offered

### ISSUE THREAD

**Issue by ssokolow** [ionrock/cachecontrol#55]
I've been thinking about the design of `BaseHeuristic` and, while the new design seems good as a base class (for the uses I've thought of so far), I think that, for common-case uses, it's going to result in a lot of people who don't have the time to become HTTP 1.1 experts reinventing boilerplate and introducing subtle bugs in their header parsing and resetting code.

There should probably be a subclass with a name like `SimpleBaseHeuristic` where, instead of `update_headers(self, response)` and `warning(self, response)`, you override `set_expiry(self, response, current_expiry)` and `return` the new expiry value.

(That is, a subclass which provides a single, shared implementation of going from multiple subtly different HTTP headers to one "this is how long it'll last" number and then back again and also handles the warning 110/113 selection automatically )

If you don't beat me to it, I'll try to write it as soon as I can figure out the least hacky way to call `CacheController.parse_cache_control` from a `BaseHeuristic` subclass so I can access the value of `max-age` without duplicating the `Cache-Control` parsing code.

**Comment by ionrock** [comment]
Stephan Sokolow writes:

> I've been thinking about the design of BaseHeuristic and, while the new design seems good as a base class for the uses I've thought of so far, I think that, for common-case uses, it's going to result in a lot of people who don't have the time to become HTTP 1.1 experts reinventing boilerplate and introducing subtle bugs in their header parsing and resetting code.
>
> There should probably be a subclass with a name like `SimpleBasicHeuristic` where, instead of `update_headers(self, response)` and `warning(self, response)`, you override `set_expiry(self, response, current_expiry)` and `return` the new expiry value.
>
> (That is, a subclass which provides a single, shared implementation of going from multiple subtly different HTTP headers to one "this is how long it'll last" number and then back again and also handles the warning 110/113 selection automatically )
>
> If you don't beat me to it, I'll try to write it as soon as I can
> figure out the least hacky way to call
> `CacheController.parse_cache_control` from a `BaseHeuristic` subclass
> so I can access the value of `max-age` without duplicating the
> `Cache-Control` parsing code.


There is a `cachecontrol.heuristics.ExpiresAfter` that takes the smae
arguments of a `datetime.timedelta` object. It doesn't update the
warning to a 113 after 24 hours, but now that can be fixed.

Like I said, this is still pretty new, so common use cases to include
are certainly accepted.

You are correct though that it would be helpful to expose the cache
control header parsing as a utility that the heuristic code could
easily import.
