### ISSUE TITLE
Support caching 301 Moved Permanently

### ISSUE THREAD

**Issue by ionrock** [ionrock/cachecontrol#56]
In requests issue [#2409](https://github.com/kennethreitz/requests/issues/2409#issuecomment-70224889) there is a discussion of removing the specialized history cache that maintains permanent redirects. A solution would be to recommend CacheControl, but unfortunately, as CacheControl assumes requests will handle 301s, it isn't supported. 

CacheControl should handle 301s by always caching the response unless other caching headers are included that change the behavior. Similarly, any cache busting headers should be respected as usual.

**Comment by Lukasa** [comment]
Does this need to generalise to other 3XX codes, or does CC already handle those?

**Comment by ionrock** [comment]
304 is handled as it is related to conditional requests. CC explicitly doesn't cache 300, which is a holdover from httplib2.

I'll take a closer look to see what other 3xx codes could/should be supported.
