### ISSUE TITLE
Is there a good way to get the path of the underlying cached file for a given URL?

### ISSUE THREAD

**Issue by hiltonc** [ionrock/cachecontrol#63]
I'm using CacheControl as a wrapper around session with a FileCache. It works great, but, given a URL, I'd like to be able to get the path to the underlying file (if it has been cached). This would greatly speed up my use of it, because without it I need to read the contents of the file through the session, then write them out to the file system again for use in a command external to my program.

I've been looking through the code but I can't find an obvious way to do that. I can directly access the FileCache, but I'm having trouble converting the URL to a cache key. Is this use case supported, or can it be?

**Comment by hiltonc** [comment]
I got something to work:

    session_file_cache = FileCache(my_cache_dir)
    session = CacheControl(requests.session(), cache=session_file_cache)
    key = CacheController().cache_url(my_url)
    path = session_file_cache._fn(key)

I suspect this is a little brittle, so if this could be added to the public API that would be great.

**Comment by ionrock** [comment]
@hiltonc I added a `cachecontrol.caches.file_cache.url_to_file_path` that accepts the file cache instance and a URL to generate the path. Hope that helps!

**Comment by hiltonc** [comment]
Sorry I didn't try this sooner. It work great, thank you!
