### ISSUE TITLE
Memcache as a storage backend

### ISSUE THREAD

**Issue by jinpark** [ionrock/cachecontrol#73]
After redis gets sorted out, memcache please? :)

**Comment by ionrock** [comment]
I'm going to go ahead an close this one. If you create your own memcache backend, please let me know and I'll add it to the docs for reference. Outside of that, I don't plan on adding more backends to the core of CacheControl in favor of using recommended third party drivers.

**Comment by jinpark** [comment]
Understood. I'll try to work something out :)

**Comment by ionrock** [comment]
@jinpark Thanks!
