### ISSUE TITLE
Accessing the original response and status code

### ISSUE THREAD

**Issue by rouge8** [ionrock/cachecontrol#74]
Is it possible to access the original response/status code of cached responses? This would be useful for measuring cache hits/misses.

**Comment by ionrock** [comment]
@rouge8 The status code should be the same, with the exception of a conditional request, in which case you'd get a 304 Not Modified, but the cached response is 200. Also, CacheControl adds a `from_cache` attribute to the responses so you can assert whether it came from the cache or not. 

Please let me know if I'm misunderstanding you! Also apologies for the slow response.

**Comment by rouge8** [comment]
> Also, CacheControl adds a `from_cache` attribute to the responses so you can assert whether it came from the cache or not.

That's exactly what I was looking for! I didn't see any mention of this in the docs.

**Comment by ionrock** [comment]
Sounds like this can be closed.
