### ISSUE TITLE
Documentation doesn't explain how to force read from cache even if expired

### ISSUE THREAD

**Issue by yobuntu** [ionrock/cachecontrol#75]
This is very usefull when dealing whit paginated api. ( exemple : github api).

when a query have a lot of response, there is pagination whith header links to follow.
when a query is on several pages a 304 not modified, mean not modified for all of them, so no need to make the conditionnal query for all the next pages.
I can't find a way to go read directly in the cache without trying a query first

**Comment by ionrock** [comment]
@yobuntu If I understand you correctly, you should probably consider writing a [heuristic](http://cachecontrol.readthedocs.org/en/latest/custom_heuristics.html#caching-heuristics) that ensures each request is cacheable. I suspect that the site you're requesting might be setting header that don't allow caching since the results might be changing. For example, if you were to request a set of pages listed by date, the "0" page will change with each subsequent page getting updated as well. 

Let me know if that doesn't help and apologies for a slow reply.

**Comment by yobuntu** [comment]
@ionrock, i'm sorry , if think my problem is the oposite: 
you are right, when the first page is modified, all subsequent pages are modified as well.
but when the first page isn't modified, it means none of the other pages are modified. In this case i don't need to try and get a 304 response for each page. I know i could get the response directly from the cache wihtout sending a request first.
the pages are in the cache since i can get them after i get a 304 response. I just don't know how to read them directly.


I'll try to expose exactly my use case:

I make requests to github api.
i want to get all issues for a projet, and lets say there are 1 000 issues.
so github send me a response with the 100 first issues, and a header link to the next page.
when the first page is not modified, i know that no other pages are modified, so i want to read them directly from the cache without waiting for 9 more 304 not modified responses.

what i have understood about heuristic is that is a strategy to choose when and for how long to cache a request/response. but, as all my request have an etag they are cached, so i think the default heuristic is ok. but maybe i didn't understand well.

**Comment by ionrock** [comment]
@yobuntu Even though they have an etag, the responses might have some other cache busting header. If you were to create a heuristic, you could inspect the headers and replace them accordingly. For example, if the `Cache-Control` header was set to `no-cache`, you'd want to set it to `public` instead. Unfortunately, it is dependent on the headers of the response, so you might need to experiment to see what works.

HTH

**Comment by ionrock** [comment]
I'm going to go ahead an close this one.
