### ISSUE TITLE
When are contents written to the path returned by url_to_file_path [question]

### ISSUE THREAD

**Issue by ElDeveloper** [ionrock/cachecontrol#77]
I'm able to retrieve the path where contents will be written by a FileCache object, however as the function's docstring indicates there's no guarantee that this file will exist. What I'm finding is that for most URLs I try, the contents are written immediately as I perform the request, see the two examples below.

When I do the following, the path doesn't exist:

```python
In [54]: from cachecontrol.caches import FileCache

In [55]: from cachecontrol.caches.file_cache import url_to_file_path

In [56]: from contextlib import contextmanager

In [57]: from tempfile import gettempdir

In [58]: file_cache = FileCache(gettempdir())

In [60]: from cachecontrol import CacheControl

In [61]: sess = CacheControl(requests.Session(), cache=file_cache)

In [62]: url = ('http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?retmax=1'
   ....:        '00&retmode=text&tool=skbio&db=nucleotide&id=459567&rettype=fas'
   ....:        'ta&retstart=0&email=foo@bar.com')

In [63]: req = sess.get(url)

In [64]: cached_fp = url_to_file_path(url, file_cache)

In [65]: from os.path import exists

In [67]: _  = req.content

# the file doesn't seem to exist
In [68]: exists(cached_fp)
Out[68]: False
```

However, if I try this with another URL that has the same contents, the file exists.

```python
In [69]: other_url = 'https://gist.githubusercontent.com/ElDeveloper/e0144eaf196f3a641409/raw/f14a6ff47b880537da3067b322526a91124ff742/-'

In [70]: req = sess.get(other_url)

In [71]: cached_fp = url_to_file_path(other_url, file_cache)

# the file exists YAY :D
In [72]: exists(cached_fp)
Out[72]: True
```

I don't know if this is something specific to the server I'm trying to retrieve the data from or if this is an expected behavior of FileCache. Any help is greatly appreciated.

**Comment by ionrock** [comment]
@ElDeveloper Can you see what sort of headers each request is returning? The initial URL might be configured to return a "Cache-Control: no-cache" header, where as a gist is likely to allow caching.

**Comment by ElDeveloper** [comment]
@ionrock thanks for the pointer! Looking at the responses that I get from both URLs, the one that's not caching the contens returns `Cache-Control:	private` and the one that is caching the contents returns `Cache-Control:	max-age=300, public`. Is there any way to force CacheControl to always cache the fetched content?

**Comment by ionrock** [comment]
@ElDeveloper Yes! You can use a custom [heuristic](http://cachecontrol.readthedocs.org/en/latest/custom_heuristics.html). The heuristic API is somewhat raw in that its goal is to allow you update headers, but it should do the trick with a little trial and error.

**Comment by ElDeveloper** [comment]
@ionrock, that's awesome!! :+1: Thanks a lot!
