### ISSUE TITLE
Chunked responses are not cached

### ISSUE THREAD

**Issue by bdeeney** [ionrock/cachecontrol#81]
Otherwise cacheable chunked responses (indicated by a response header `Transfer-Encoding: chunked`) are not cached by CacheControl when `requests>=2.6.1` is used.

It seems this issue appeared with the inclusion of shazow/urllib3@f21c2a2b73e4256ba2787f8470dbee6872987d2d in the `requests` codebase via kennethreitz/requests@5fcd843eb23e8e84cd5f60c6d372ef4d678f80fe.

Example script demonstrating the issue:

```python
In [1]: import requests
In [2]: from requests.packages import urllib3
In [3]: from cachecontrol import CacheControl
In [4]: urllib3.disable_warnings()  # https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning
In [5]: sess = requests.session()
In [6]: cached_sess = CacheControl(sess)
In [7]: # non-chunked response
In [8]: response = cached_sess.get('http://httpbin.org/cache/60')
In [9]: response.headers.get('transfer-encoding') is None
Out[9]: True
In [10]: response.from_cache
Out[10]: False
In [11]: response = cached_sess.get('http://httpbin.org/cache/60')
In [12]: response.from_cache
Out[12]: True
In [13]: # chunked response
In [14]: response = cached_sess.get('https://tor.eff.org/')
In [15]: response.headers.get('transfer-encoding') == 'chunked'
Out[15]: True
In [16]: response.from_cache
Out[16]: False
In [17]: response = cached_sess.get('https://tor.eff.org/')
In [18]: response.from_cache
Out[18]: False
In [19]:
```

**Comment by jrydberg** [comment]
I'm running into this when trying to cache responses from api.github.com

**Comment by ionrock** [comment]
@jrydberg Can you try @bdeeney's patch to see if that fixes things?

**Comment by stickystyle** [comment]
@ionrock I was experiencing this same issue, using the patch from @bdeeney solved it.

**Comment by jrydberg** [comment]
@ionrock It does.

**Comment by ionrock** [comment]
This should be fixed. Closing this out.

**Comment by bdeeney** [comment]
@ionrock Thanks for identifying a solution for this issue.  Any chance of cutting a pypi release that includes the changes in a10539c?

**Comment by ionrock** [comment]
@bdeeney I'd like to, but I've hoped to get some feedback to ensure it is working as expected. Have you been using the latest ref anywhere?

**Comment by bdeeney** [comment]
@ionrock Makes sense.  I've not tested the latest ref yet, but will do so and provide feedback.

**Comment by ionrock** [comment]
@bdeeney Thanks! Let me know how it works out and I'll ping some other folks to do the same.

**Comment by bdeeney** [comment]
@ionrock I tested 4746b90 and confirmed that chunked responses are cached as expected.  We've been running this ref in production for several days with no issues.
