### ISSUE TITLE
Detect Failed Downloads

### ISSUE THREAD

**Issue by dstufft** [ionrock/cachecontrol#83]
Currently (I think) the caching code assumes that if we call ``read()`` on the file and it's closed that we've successfully downloaded the file. This caused issues for someone in pip (see https://bitbucket.org/zzzeek/sqlalchemy/issue/3447/unable-to-install-sqlalchemy). I'm not sure what the best way of handling this would be.

**Comment by ionrock** [comment]
@dstufft I think step one will be to check for a Content-Length and purge the cached item if the length and the actual file don't match. Longer term, I'll plan on some sort of a hook that can assert a response is valid before using the cached value.
