### ISSUE TITLE
No logging

### ISSUE THREAD

**Issue by toolforger** [ionrock/cachecontrol#85]
I'm not seeing any logging statements.
Issue I'm having right now is that cachecontrol isn't caching responses I'd have expected to get cached, but I have no idea why, not even after single-stepping through it: I'm seeing all the turns where it decides it's not going to cache it right now, and I don't know which of these decisions is right (or maybe all of them are right and the website just isn't sending the right headers).

**Comment by toolforger** [comment]
Oh, I forgot to mention - I'd be willing to submit a PR, given guidelines and hints as far as applicable.

**Comment by ionrock** [comment]
@toolforger I'm going to close this one as it is potentially fixed and documented in #92. Can you update #92 with any updates?
