### ISSUE TITLE
CacheControl should log its decisionmaking

### ISSUE THREAD

**Issue by toolforger** [ionrock/cachecontrol#92]
All the decisions that lead to CacheControl entering something into the cache or not, retrieving something from the cache or not, should be logged at DEBUG level.
Reason: HTTP caching is far more complex and influenced by far more factors than most developers that will use CacheControl are aware. If developers are searching for the cause of unexpected behaviour (a.k.a. a bug), knowledge of the decisionmaking will help them determine whether they should look in their own logic, the server's logic, or CacheControl's logic.

**Comment by ionrock** [comment]
@toolforger I believe I merged your logging additions. Can we close this one?

**Comment by toolforger** [comment]
Do you want to guarantee to cachecontrol users that all decision points are logged?
It would be very valuable to them. In that case, you'd want to (a) check that I didn't overlook any decision points (I tried to be thorough but can't be sure), and (b) document that guarantee in the docs so users will actually start to rely on it.

Whether you accept that or not, I'm fine with this one being closed, my work is done unless you have questions :-)
