### ISSUE TITLE
Cache entries may be cleared prematurely

### ISSUE THREAD

**Issue by toolforger** [ionrock/cachecontrol#94]
`CacheController.cached_request` clears out cache entries if they were stale, even if staleness happened just because the cache entry was older than what the request required.
A later request may tolerate a higher age, so the cache entry could still be useful.

In the following scenario, this will cause a refetch that should have been served from the cache:
- Request 1 specifies a tight max-age, causing the cache to drop the entry and try fetching a new result
- For some reason, that result is not entered into the cache (temporary failure, cache control headers, whatever)
- Request 2 needs to specify a relaxed max age, so the original cache entry would have been returned if it were still in the cache

In the following scenario, this will fail to return a cached entry where it could have:
- First three steps as above
- Request 2, when fetching from the server, hits some temporary problem.

Admittedly, neither scenario is very likely, but given that caching is such a foundational part that people expect to "just work", I think that even this stone shouldn't be left unturned.

**Comment by ionrock** [comment]
@toolforger While I think I can see how this can happen, I believe the heuristics would be the best way to work around this issue on a per-site basis. Let me know if I'm misunderstanding anything, especially any good examples you're hitting in the wild. Thanks!
