### ISSUE TITLE
FileNotFound error with PUT and FileCache

### ISSUE THREAD

**Issue by jseabold** [ionrock/cachecontrol#99]
I'm using the CacheControlAdapter with a FileCache and I'm getting a FileNotFound error issuing a PUT request. Bug or user error? Stepping through the debugger. It doesn't look like the PUT request is ever cached to be deleted so the file shouldn't exist, or am I missing something?

```
> /Users/user/.py34/lib/python3.4/site-packages/cachecontrol/caches/file_cache.py(107)delete()
    106         if not self.forever:
--> 107             os.remove(name)
    108

ipdb> u
> /Users/user/.py34/lib/python3.4/site-packages/cachecontrol/adapter.py(108)build_response()
    107             cache_url = self.controller.cache_url(request.url)
--> 108             self.cache.delete(cache_url)
    109

ipdb> u
> /Users/user/.py34/lib/python3.4/site-packages/requests-2.7.0-py3.4.egg/requests/adapters.py(437)send()
    435                 raise
    436
--> 437         return self.build_response(request, resp)
```

**Comment by ionrock** [comment]
@jseabold That does look like a bug. A PUT should invalidate a cached resource, so it looks like it is trying to delete a file that doesn't exist. I'm not sure why it still found it in the cache at all though. Could another process / thread have already deleted the file?

**Comment by ionrock** [comment]
@jseabold Haven't heard back from you on this one, so I'm going to go ahead and close this one. Please feel free to reopen if you have a test case to reproduce this issue.
